'' -*- mode: freebasic -*-
#lang "fblite"
#include "matrix/cec/bin/dialog/backend.bi"
#include "matrix/cec/bin/dialog/popback.bi"
#include "matrix/cec/bin/dialog/games.bi"
#include "matrix/cec/bin/dialog/browser/edges.bi"
#include "matrix/cec/bin/dialog/browser/http/agentHttp.bi"
#include "matrix/cec/bin/dialog/browser/http/filename/name.bi"
#include "matrix/cec/bin/dialog/browser/http/tabs/http.bi"
#include "matrix/cec/bin/dialog/browser/http/oracles/database/previews/living.bi"
#include "matrix/cec/bin/dialog/browser/http/oracles/database/views/script.bi"
#include "matrix/cec/bin/dialog/browser/http/oracles/script/fbscript.bi"
#include "matrix/cec/bin/dialog/browser/http/property/pattern.bi"
#include "matrix/cec/bin/dialog/browser/http/graphic/link.bi"
#include "matrix/cec/bin/dialog/browser/http/plot/graphic.bi"
#include "matrix/cec/bin/dialog/browser/http/agent/zero.bi"
#include "matrix/cec/bin/dialog/browser/http/decimal/unit.bi"
#include "matrix/cec/bin/dialog/browser/http/global/math.bi"
#include "matrix/cec/bin/dialog/browser/http/record/class/solverMath.bi"
#include "matrix/cec/bin/dialog/browser/options/equation/object.bi"
#include "matrix/cec/bin/dialog/browser/options/items/relic.bi"
#include "matrix/cec/bin/dialog/browser/options/tables/cols/align.bi"
#include "matrix/cec/bin/dialog/browser/options/tables/rows/align.bi"
#include "matrix/cec/bin/dialog/browser/caption/vista/real.bi"
#include "matrix/cec/bin/dialog/browser/algorithm/code.bi"
#include "matrix/cec/bin/dialog/browser/localhost/filename.bi"
#include "matrix/cec/bin/dialog/browser/extension/install.bi"
#include "matrix/cec/bin/dialog/browser/extension/drizzle/extension.bi"
#include "matrix/cec/bin/dialog/browser/extension/packages/extension.bi"
#include "matrix/cec/bin/dialog/browser/extension/web/extension.bi"
#include "matrix/cec/lib/frygmeoc.net.http.bi"
Sub Main()

Print "Hello, World!"

End Sub